base_url = "https://shotor.com"
title = "shotor.com"
description = "shotor software development services"
default_language = "en"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
